- hosts: localhost

  vars:
    proxy_env:
      PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
      TERM: xterm-256color
      SHELL: /bin/bash

  tasks:

    - name: remove
      shell: dd if=/dev/null of=/home/user/.xsession-errors
      environment: "{{ proxy_env }}"

    - name:  Instalacja paczek xkasnet bionic
      apt:
        name:
          - chromium-browser
          - chromium-browser-l10n
          - chromium-codecs-ffmpeg-extra
        state: latest
        force: yes
        update_cache: yes
      environment: "{{ proxy_env }}"
